Repository cds-snc/cds-aws-lz, pull requests merged in 2023-02, with the labels that each got.

#173 fix: format ops passwords + length
  bin/create_ops_users.sh
Labels: AWS

#174 fix: update password length
  bin/update_ops_users_passwords.sh
Labels: AWS

#175 Feat/delete migrated scripts
  bin/create_ops_users.sh
  bin/invoke_customizations_all.sh
  bin/invoke_customizations_all_and_prod.sh
  bin/invoke_customizations_ou.sh
  bin/invoke_customizations_testbed.sh
  bin/migrate/create_awsctexec_role.sh
  bin/migrate/get_lambda_resource_policies.sh
  bin/migrate/invoke_account.sh
  bin/migrate/remove_aft_created_resources.sh
  bin/one-offs/add_admin_policy.sh
  bin/update_ops_users_passwords.sh
Labels: Nuts and bolts

#176 feat: add controls for enabling CT Log validation
  terragrunt/org_account/organization/guardrails.tf
  terragrunt/org_account/organization/modules/control/guardrail.tf
  terragrunt/org_account/organization/modules/control/inputs.tf
  terragrunt/org_account/organization/modules/global_controls/inputs.tf
  terragrunt/org_account/organization/organizations.tf
Labels: Security | Sécurité, AWS

#178 feat: add an SCP on the root user.
  terragrunt/org_account/organization/scp.tf
Labels: High Priority | Haute priorité, Security | Sécurité, AWS

#179 feat: enable guardrail disallowing creation of access keys for the root
  terragrunt/org_account/organization/guardrails.tf
  terragrunt/org_account/organization/modules/global_controls/guardrails.tf
  terragrunt/org_account/organization/scp.tf
Labels: Security | Sécurité, AWS

#183 feat: stop alerting on aft-failure-notifications
  terragrunt/aft/notifications/aft-notifications.tf
Labels: AWS

#184 feat: enable trusted access to CF Stacksets
  terragrunt/org_account/organization/organizations.tf
Labels: AWS

#188 feat: re-enable aft-failure-notification slack integration
  terragrunt/aft/notifications/aft-notifications.tf
Labels: AWS
